FORMAT: 1A


# Llama lists API


# Group Lists


## Lists Collection [/api/lists]


### Get All Lists [GET /api/lists/{id}]

- Parameter

    - id: `Eugene` - The Login Of The User


- Response 200 (application/json)

    - Attributes

        - Include Lists


# Data Structures


## Lists (object)

- id: `570c111e170218c32f1b1890` (string) - The ID of the list

- title: `My awesome list` (string) - The Title Of The List

- image: `list-background-1` (string) - The Image Of The List


# Group Tasks


# Group Users
